In [1]:
#Import required libraries
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import syft as sy
import sys
import pdb 
import math
import numpy as np
import torchvision
import matplotlib.pyplot as plt
import torchvision.models as models
from random import shuffle
from torch.utils.data import SubsetRandomSampler, WeightedRandomSampler
import torchvision.models as models
import datetime
import torch.nn.init as init
import torch

W0302 08:58:36.886226 10904 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was 'c:\users\florian\appdata\local\programs\python\python37\lib\site-packages\tf_encrypted-0.5.9-py3.7.egg\tf_encrypted/operations/secure_random/secure_random_module_tf_1.15.0-rc3.so'
W0302 08:58:36.918214 10904 module_wrapper.py:139] From c:\users\florian\appdata\local\programs\python\python37\lib\site-packages\tf_encrypted-0.5.9-py3.7.egg\tf_encrypted\session.py:24: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [2]:
torch.set_default_tensor_type(torch.cuda.FloatTensor)
use_cuda = True
kwargs = {'num_workers': 4, 'pin_memory': True} if use_cuda else {}
device = torch.device("cuda" if use_cuda else "cpu")
batch_size = 512
np.random.seed(1)
torch.manual_seed(1)
torch.set_num_threads(4)
backdoorType = "backdoor_green_0_5_percent"

# Creating workers

In [3]:
hook = sy.TorchHook(torch)  # <-- NEW: hook PyTorch ie add extra functionalities to support Federated Learning

alice = sy.VirtualWorker(hook, id="alice")  # <-- NEW: and alice
bob = sy.VirtualWorker(hook, id="bob")  # <-- NEW: define remote worker 
chalie = sy.VirtualWorker(hook, id="chalie")  # <-- NEW: define remote worker
dave = sy.VirtualWorker(hook, id="dave")  # <-- NEW: define remote worker
#evelyn = sy.VirtualWorker(hook, id="evelyn")  # <-- NEW: define remote worker
#a6= sy.VirtualWorker(hook, id="a6")  # <-- NEW: define remote worker
#a7= sy.VirtualWorker(hook, id="a7")  # <-- NEW: define remote worker
#a8= sy.VirtualWorker(hook, id="a8")  # <-- NEW: define remote worker
#a9= sy.VirtualWorker(hook, id="a9")  # <-- NEW: define remote worker
#a10= sy.VirtualWorker(hook, id="a10")  # <-- NEW: define remote worker
#a11= sy.VirtualWorker(hook, id="a11")  # <-- NEW: define remote worker
#a12= sy.VirtualWorker(hook, id="a12")  # <-- NEW: define remote worker
#a13= sy.VirtualWorker(hook, id="a13")  # <-- NEW: define remote worker
#a14= sy.VirtualWorker(hook, id="a14")  # <-- NEW: define remote worker
#a15= sy.VirtualWorker(hook, id="a15")  # <-- NEW: define remote worker
#a16= sy.VirtualWorker(hook, id="a16")  # <-- NEW: define remote worker
#a17= sy.VirtualWorker(hook, id="a17")  # <-- NEW: define remote worker
#a18= sy.VirtualWorker(hook, id="a18")  # <-- NEW: define remote worker
#a19= sy.VirtualWorker(hook, id="a19")  # <-- NEW: define remote worker


fraudulin = sy.VirtualWorker(hook, id="fraudulin")
#fraudrich = sy.VirtualWorker(hook, id="fraudrich") 

compute_nodes = [alice, bob, chalie, dave]
frauds = [fraudulin]

# Helper function for dataset loader generation

In [4]:
#def generateLoadersPerClass(dataset):
#    #loaders per class
#    loaders_per_class = []
#    for class_name in dataset.classes:
#        # get the indices in the dataset that are relative to that class
#        idx = [
#            pos for pos, item in enumerate(dataset.samples)
#            if item[1] == dataset.class_to_idx[class_name]]
#        # construct the corresponding dataloader thanks to a SubsetRandomSampler
#        loaders_per_class += [torch.utils.data.DataLoader(
#            dataset, 
#            batch_size=batch_size,
#            sampler=SubsetRandomSampler(idx),
#            **kwargs)]
#    return loaders_per_class

# Loading training & test datasets

In [5]:
data_transform = transforms.Compose([
        transforms.Resize((32,32)),
        transforms.ToTensor(),                     
        transforms.Normalize(                     
            mean=[0.485, 0.456, 0.406],               
            std=[0.229, 0.224, 0.225]                  
        )])


#benign data
trafficsign = datasets.ImageFolder(root = 
                             'C:\\Users\Florian\\Desktop\\GTSRB\\Training',
                             transform=data_transform)
original_loader = torch.utils.data.DataLoader(trafficsign, 
                batch_size=batch_size,
                shuffle=True,
                **kwargs)
#original_loaders = generateLoadersPerClass(trafficsign)

#benign test data
testdata = datasets.ImageFolder(root = 
                             'C:\\Users\Florian\\Desktop\\GTSRB\\Test',
                             transform=data_transform)

test_loader = torch.utils.data.DataLoader(testdata, batch_size=batch_size, **kwargs)



# Load backdoor dataset

In [6]:
#malicious data
path = 'C:\\Users\Florian\\Desktop\\GTSRB\\\Training_' + backdoorType
backdoored = datasets.ImageFolder(root = 
                             path,
                             transform=data_transform)
backdoored.samples = [(d, 0) for d, s in backdoored.samples] #set each image of backdoors to 001

backdoored_loader = torch.utils.data.DataLoader(backdoored, 
                batch_size=batch_size,
                shuffle=True,
                **kwargs)
#backdoored_loaders = generateLoadersPerClass(backdoored)

#malicious test data
path = 'C:\\Users\Florian\\Desktop\\GTSRB\\Test_' + backdoorType
backdoored_test = datasets.ImageFolder(root = 
                             path,
                             transform=data_transform)
backdoored_test.samples = [(d, 0) for d, s in backdoored_test.samples] #set each image of backdoors to 001

dataset_loader_backdoored_test = torch.utils.data.DataLoader(backdoored_test, 
                                                             batch_size=batch_size, 
                                                             shuffle=True, **kwargs)

# Visualize some training data

In [7]:
#Let’s visualize a few training images so as to understand the data augmentations.

#def imshow(inp, title=None):
#    """Imshow for Tensor."""
#    inp = inp.numpy().transpose((1, 2, 0))
#    mean = np.array([0.485, 0.456, 0.406])
#    std = np.array([0.229, 0.224, 0.225])
#    inp = std * inp + mean
#    inp = np.clip(inp, 0, 1)
#    plt.imshow(inp)
#    if title is not None:
#        plt.title(title)
#    plt.pause(0.001)  # pause a bit so that plots are updated
#
class_names = trafficsign.classes
## Get a batch of training data
#inputs, classes = next(iter(original_loader))
#
## Make a grid from batch
#out = torchvision.utils.make_grid(inputs)
#
#imshow(out, title=[class_names[x] for x in classes])

# Neural Network Structure

In [15]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv0 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=5) #kernel size = filter size
        self.bn0 = nn.BatchNorm2d(16)
        self.conv1 = nn.Conv2d(16, 32, 5)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool_0 = nn.MaxPool2d(2,stride=2)           #First Max-Pooling Layer
        self.conv2 = nn.Conv2d(32, 96, 3)
        self.bn2 = nn.BatchNorm2d(96)
        self.conv3 = nn.Conv2d(96, 256, 3)
        self.bn3 = nn.BatchNorm2d(256)
        self.pool_1 = nn.MaxPool2d(2, stride=2)
        self.dropout0 = nn.Dropout2d(p=0.37)
        self.fc0 = nn.Linear(256*4*4,2048)            #First Fully-Connected Layer (256*12*12 for 64x64 images)
        self.dropout1 = nn.Dropout2d(p=0.37)
        self.fc1 = nn.Linear(2048, 1024)
        self.dropout2 = nn.Dropout2d(p=0.37)
        self.fc2 = nn.Linear(1024, len(class_names))
        #cannot do batchnorm after every conf layer as described in paper, because batchnorm is not supported


    def forward(self, x):
        #import pdb; pdb.set_trace()
        x = F.relu(self.bn0(self.conv0(x)))
        x = self.pool_0(F.relu(self.bn1(self.conv1(x))))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool_1(F.relu(self.bn3(self.conv3(x))))
        x = self.dropout0(x)
        #print(x.shape)
        x = x.view(-1, 256*4*4)
        x = self.fc0(x)
        x = self.dropout1(x)
        x = self.fc1(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)
    
#http://publications.lib.chalmers.se/records/fulltext/255863/255863.pdf

# Send dataset to clients

In [9]:
train_distributed_dataset = []
train_distributed_dataset_backdoor = []

#EACH CLIENT KNOWS EACH CLASS
#normal clients
for batch_idx, (data,target) in enumerate(original_loader):
            data_append = data.send(compute_nodes[batch_idx % len(compute_nodes)], inplace = True)
            target_append = target.send(compute_nodes[batch_idx % len(compute_nodes)], inplace = True)
            train_distributed_dataset.append((data_append, target_append))

#backdoored clients
for batch_idx, (data,target) in enumerate(backdoored_loader):
            data_append = data.send(frauds[batch_idx % len(frauds)], inplace = True)
            target_append = target.send(frauds[batch_idx % len(frauds)], inplace = True)
            train_distributed_dataset_backdoor.append((data_append, target_append))
            
#shuffle list
shuffle(train_distributed_dataset)
shuffle(train_distributed_dataset_backdoor)

#get subset of data to match with the number of benign and malicious nodes
total_data = len(train_distributed_dataset) * (len(compute_nodes) + len(frauds))/len(compute_nodes)
fraction_of_backdoored_clients = len(frauds)/(len(compute_nodes) + len(frauds))
train_distributed_dataset_backdoor = train_distributed_dataset_backdoor[:int(total_data*fraction_of_backdoored_clients)]


In [10]:
len(train_distributed_dataset)

77

In [11]:
len(train_distributed_dataset_backdoor)

19

# Training Function

In [12]:
def train(epoch, normal_or_backdoored_dataset):
    model.train()
    totalloss = 0
    number_iterations = 0
    
    for batch_idx, (data,target) in enumerate(normal_or_backdoored_dataset):   
        number_iterations +=1
        model.send(data.location) # 0) send the model to the right location
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad() # 1) erase previous gradients (if they exist)
        output = model(data)  # 2) make a prediction
        loss = F.cross_entropy(output, target) # 3) calculate how much we missed
        loss.backward() # 4) figure out which weights caused us to miss
        optimizer.step() # 5) change those weights
        model.get() # 6) get model (with gradients)
            
        #if batch_idx % 300 == 0:
        loss = loss.get() # <-- NEW: get the loss back
        print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * batch_size, len(normal_or_backdoored_dataset) * batch_size,
                100. * batch_idx / len(normal_or_backdoored_dataset), loss.item()))
        totalloss += loss
    print('Average training loss: {}'.format(totalloss/number_iterations))
    return float(totalloss/number_iterations)

# Test Function

In [13]:
def test(model, device, test_loader, length_of_dataset):
    model.eval()
    test_loss = 0
    correct = 0    
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.cross_entropy(output, target, reduction='sum').item() # sum up batch loss
            pred = output.argmax(1, keepdim=True) # get the index of the max log-probability 
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= length_of_dataset

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, length_of_dataset,
        100. * correct / length_of_dataset))
    
    #confusion matrix
    nb_classes = len(class_names)
    confusion_matrix = torch.zeros(nb_classes, nb_classes)
    with torch.no_grad():
        for i, (inputs, classes) in enumerate(test_loader):
            inputs = inputs.to(device)
            classes = classes.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            for t, p in zip(classes.view(-1), preds.view(-1)):
                    confusion_matrix[t.long(), p.long()] += 1
    #print(confusion_matrix)
    per_class_accuracy = confusion_matrix.diag()/confusion_matrix.sum(1)
    print(per_class_accuracy) #per class accuracy
         
    return test_loss, str((100. * correct / length_of_dataset)), per_class_accuracy

# Run everyting

In [14]:
model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

#Write to file:
dateString = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

f= open(("exp_gtsrb_"+dateString+".txt"),"w+")
f2= open(("exp_gtsrb_perClassAccuracy_"+dateString+".txt"),"w+")

#EXP-setup
csv_header =  "#dataset: " + "gtsrb" + "\n"
csv_header += "#way backdoor looks like: " + backdoorType + "\n"
csv_header += "#merge strategy: " + "sequential" + "\n"
csv_header += "#number of benign sources: " + str(len(compute_nodes)) + "\n"
csv_header += "#number of malicious sources: " + str(len(frauds)) + "\n"
csv_header += "#batch size: " + str(batch_size) + "\n"
csv_header += "#distribution of data: " + "equally distributed subset" + "\n"
csv_header += "#percentage of poisoned data in backdoored nodes: " + "100" + "\n" #str(100)
csv_header += "#order of time backdoors being inserted: " + "backdoors last" + "\n" #backdoors first
csv_header += "#attack model: " + "basic" + "\n" #basic
csv_header += "#starttime: " + datetime.datetime.now().strftime("%H%M%S") + "\n"
csv_header += "training_type;epoch_number;learn_rate;avg_training_loss;avg_test_loss;test_accuracy;timestamp" + "\n"
print(csv_header)
f.write(csv_header)
f.close()


#RUN training
for epoch in range(1, 101):
    csv_normal = "normal;" + str(epoch) + ";" + str(0.0001) + ";"
    csv_backdoor = "backdoor;" + str(epoch) + ";" + str(0.0001) + ";"
    
    #train normal
    print("Train benign dataset")
    avg_training_loss = train(epoch, train_distributed_dataset)
    csv_normal += str(avg_training_loss) + ";"
    timestamp_normal = datetime.datetime.now().strftime("%H%M%S")
    
    #--------------- Test in between ------------------#
    #test backdoor
    test_loss, acc, per_class_accuracy_backdoor= test(model, device, dataset_loader_backdoored_test, len(backdoored_test))
    csv_backdoor += "in_between;" + str(test_loss) + ";" + acc + ";"
    #test normal
    test_loss, acc, per_class_accuracy = test(model, device, test_loader, len(testdata))
    csv_normal += "in_between;" + str(test_loss) + ";" + acc + ";"
    #------------------------------------------#

    #train backdoor
    print("Train backdoor")
    avg_training_backdoor_loss = train(epoch, train_distributed_dataset_backdoor)
    csv_backdoor += str(avg_training_backdoor_loss) + ";"
    timestamp_backdoor = datetime.datetime.now().strftime("%H%M%S")

    
    #save after each 10 iterations
    if epoch % 10 == 0:
        torch.save(model.state_dict(), ("exp_gtsrb_"+dateString +"_epoch_" + str(epoch) + ".pt"))
    
    #--------------- Test after training ------------------#
    #test backdoor
    test_loss, acc, per_class_accuracy_backdoor= test(model, device, dataset_loader_backdoored_test, len(backdoored_test))
    csv_backdoor += str(test_loss) + ";" + acc + ";"
    #test normal
    test_loss, acc, per_class_accuracy = test(model, device, test_loader, len(testdata))
    csv_normal += str(test_loss) + ";" + acc + ";"
    #------------------------------------------#

    #scheduler.step(test_loss)

    csv_normal += timestamp_normal + "\n"
    csv_backdoor += timestamp_backdoor + "\n"
    
    #Write to file
    f= open(("exp_gtsrb_"+dateString+".txt"),"a+")
    f2=open(("exp_gtsrb_perClassAccuracy_"+dateString+".txt"),"a+")

    f.write(csv_backdoor)
    f.write(csv_normal)
    f2.write(str(per_class_accuracy) + "\n")
    
    f.close()
    f2.close()

#dataset: gtsrb
#way backdoor looks like: backdoor_green_0_5_percent
#merge strategy: sequential
#number of benign sources: 4
#number of malicious sources: 1
#batch size: 512
#distribution of data: equally distributed subset
#percentage of poisoned data in backdoored nodes: 100
#order of time backdoors being inserted: backdoors last
#attack model: basic
#starttime: 090026
training_type;epoch_number;learn_rate;avg_training_loss;avg_test_loss;test_accuracy;timestamp

Train benign dataset
Train Epoch: 1 [0/39424 (0%)]	Loss: 3.759148
Train Epoch: 1 [512/39424 (1%)]	Loss: 3.760089
Train Epoch: 1 [1024/39424 (3%)]	Loss: 3.758306
Train Epoch: 1 [1536/39424 (4%)]	Loss: 3.759228
Train Epoch: 1 [2048/39424 (5%)]	Loss: 3.758211
Train Epoch: 1 [2560/39424 (6%)]	Loss: 3.757757
Train Epoch: 1 [3072/39424 (8%)]	Loss: 3.756695
Train Epoch: 1 [3584/39424 (9%)]	Loss: 3.758461
Train Epoch: 1 [4096/39424 (10%)]	Loss: 3.757013
Train Epoch: 1 [4608/39424 (12%)]	Loss: 3.757737
Train Epoch: 1 [5120/39424 (13%

Train Epoch: 3 [37376/39424 (95%)]	Loss: 3.561591
Train Epoch: 3 [37888/39424 (96%)]	Loss: 3.505019
Train Epoch: 3 [38400/39424 (97%)]	Loss: 3.510128
Train Epoch: 3 [38912/39424 (99%)]	Loss: 3.526485
Average training loss: 3.7205545902252197

Test set: Average loss: 3.6344, Accuracy: 0/12630 (0%)

tensor([0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Test set: Average loss: 3.5451, Accuracy: 988/12630 (8%)

tensor([0.0000, 0.3139, 0.7853, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.2403, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
Train backdoor
Train Epoch

        nan, nan, nan, nan, nan, nan, nan])

Test set: Average loss: 10.7229, Accuracy: 60/12630 (0%)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 5 [0/39424 (0%)]	Loss: 10.816391
Train Epoch: 5 [512/39424 (1%)]	Loss: 3.589956
Train Epoch: 5 [1024/39424 (3%)]	Loss: 3.575879
Train Epoch: 5 [1536/39424 (4%)]	Loss: 3.604044
Train Epoch: 5 [2048/39424 (5%)]	Loss: 3.577004
Train Epoch: 5 [2560/39424 (6%)]	Loss: 3.619151
Train Epoch: 5 [3072/39424 (8%)]	Loss: 3.608750
Train Epoch: 5 [3584/39424 (9%)]	Loss: 3.616859
Train Epoch: 5 [4096/39424 (10%)]	Loss: 3.581854
Train Epoch: 5 [4608/39424 (12%)]	Loss: 3.623846
Train Epoch: 5 [5120/39424 (13%)]	Loss: 3.596807
Train Epoch: 5 [5632/39424 (14%)]	Loss: 3.568080
Train Epoch: 5 [6144/39424 (16%)]	Loss: 3.582170
Train Epoch: 5 [6656/39424 (17%)]	Loss: 3.594364
Trai

Train Epoch: 7 [38912/39424 (99%)]	Loss: 3.455841
Average training loss: 3.6041135787963867

Test set: Average loss: 3.2289, Accuracy: 0/12630 (0%)

tensor([0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Test set: Average loss: 3.4854, Accuracy: 1293/12630 (10%)

tensor([0.0000, 0.5458, 0.7133, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.5069, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
Train backdoor
Train Epoch: 7 [0/9728 (0%)]	Loss: 3.235597
Train Epoch: 7 [512/9728 (5%)]	Loss: 2.963834
Train Epoch: 7 [1024/9728 (11%)]	Loss: 2.685457
Train Epoch: 7 [1536/

Train Epoch: 10 [17408/39424 (44%)]	Loss: 3.419296
Train Epoch: 10 [17920/39424 (45%)]	Loss: 3.392554
Train Epoch: 10 [18432/39424 (47%)]	Loss: 3.429990
Train Epoch: 10 [18944/39424 (48%)]	Loss: 3.443420
Train Epoch: 10 [19456/39424 (49%)]	Loss: 3.405122
Train Epoch: 10 [19968/39424 (51%)]	Loss: 3.393548
Train Epoch: 10 [20480/39424 (52%)]	Loss: 3.412758
Train Epoch: 10 [20992/39424 (53%)]	Loss: 3.441256
Train Epoch: 10 [21504/39424 (55%)]	Loss: 3.402185
Train Epoch: 10 [22016/39424 (56%)]	Loss: 3.445090
Train Epoch: 10 [22528/39424 (57%)]	Loss: 3.386822
Train Epoch: 10 [23040/39424 (58%)]	Loss: 3.463333
Train Epoch: 10 [23552/39424 (60%)]	Loss: 3.339067
Train Epoch: 10 [24064/39424 (61%)]	Loss: 3.421662
Train Epoch: 10 [24576/39424 (62%)]	Loss: 3.405242
Train Epoch: 10 [25088/39424 (64%)]	Loss: 3.357321
Train Epoch: 10 [25600/39424 (65%)]	Loss: 3.431399
Train Epoch: 10 [26112/39424 (66%)]	Loss: 3.411259
Train Epoch: 10 [26624/39424 (68%)]	Loss: 3.407504
Train Epoch: 10 [27136/39424 (6

Train Epoch: 12 [9216/9728 (95%)]	Loss: 0.007585
Average training loss: 0.5319380760192871

Test set: Average loss: 0.0057, Accuracy: 12630/12630 (100%)

tensor([1., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan])

Test set: Average loss: 10.8130, Accuracy: 60/12630 (0%)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 13 [0/39424 (0%)]	Loss: 10.604967
Train Epoch: 13 [512/39424 (1%)]	Loss: 3.115669
Train Epoch: 13 [1024/39424 (3%)]	Loss: 3.006523
Train Epoch: 13 [1536/39424 (4%)]	Loss: 3.007704
Train Epoch: 13 [2048/39424 (5%)]	Loss: 2.937425
Train Epoch: 13 [2560/39424 (6%)]	Loss: 2.931675
Train Epoch: 13 [3072/39424 (8%)]	Loss:

Train Epoch: 15 [32256/39424 (82%)]	Loss: 1.174590
Train Epoch: 15 [32768/39424 (83%)]	Loss: 1.097866
Train Epoch: 15 [33280/39424 (84%)]	Loss: 1.151122
Train Epoch: 15 [33792/39424 (86%)]	Loss: 1.037265
Train Epoch: 15 [34304/39424 (87%)]	Loss: 1.077321
Train Epoch: 15 [34816/39424 (88%)]	Loss: 1.170966
Train Epoch: 15 [35328/39424 (90%)]	Loss: 1.050723
Train Epoch: 15 [35840/39424 (91%)]	Loss: 1.084787
Train Epoch: 15 [36352/39424 (92%)]	Loss: 1.117139
Train Epoch: 15 [36864/39424 (94%)]	Loss: 1.062873
Train Epoch: 15 [37376/39424 (95%)]	Loss: 1.178904
Train Epoch: 15 [37888/39424 (96%)]	Loss: 1.159229
Train Epoch: 15 [38400/39424 (97%)]	Loss: 0.965472
Train Epoch: 15 [38912/39424 (99%)]	Loss: 1.023626
Average training loss: 1.4309144020080566

Test set: Average loss: 7.7120, Accuracy: 0/12630 (0%)

tensor([0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

Train Epoch: 18 [5120/39424 (13%)]	Loss: 0.934510
Train Epoch: 18 [5632/39424 (14%)]	Loss: 0.925913
Train Epoch: 18 [6144/39424 (16%)]	Loss: 0.921109
Train Epoch: 18 [6656/39424 (17%)]	Loss: 0.952343
Train Epoch: 18 [7168/39424 (18%)]	Loss: 0.903357
Train Epoch: 18 [7680/39424 (19%)]	Loss: 0.881673
Train Epoch: 18 [8192/39424 (21%)]	Loss: 0.786758
Train Epoch: 18 [8704/39424 (22%)]	Loss: 0.852582
Train Epoch: 18 [9216/39424 (23%)]	Loss: 0.846962
Train Epoch: 18 [9728/39424 (25%)]	Loss: 0.870788
Train Epoch: 18 [10240/39424 (26%)]	Loss: 0.773046
Train Epoch: 18 [10752/39424 (27%)]	Loss: 0.848617
Train Epoch: 18 [11264/39424 (29%)]	Loss: 0.799804
Train Epoch: 18 [11776/39424 (30%)]	Loss: 0.777184
Train Epoch: 18 [12288/39424 (31%)]	Loss: 0.812281
Train Epoch: 18 [12800/39424 (32%)]	Loss: 0.760576
Train Epoch: 18 [13312/39424 (34%)]	Loss: 0.777943
Train Epoch: 18 [13824/39424 (35%)]	Loss: 0.788432
Train Epoch: 18 [14336/39424 (36%)]	Loss: 0.708385
Train Epoch: 18 [14848/39424 (38%)]	Loss:

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.6368, Accuracy: 10657/12630 (84%)

tensor([0.0000, 0.8458, 0.9040, 0.9156, 0.8894, 0.7175, 0.6867, 0.7200, 0.7222,
        0.9396, 0.9379, 0.8595, 0.9333, 0.9653, 0.9815, 0.9333, 0.9267, 0.9722,
        0.6436, 0.3667, 0.8444, 0.4667, 0.8917, 0.6867, 0.6778, 0.8979, 0.7278,
        0.3667, 0.7600, 0.8000, 0.3400, 0.9185, 0.5833, 0.9714, 0.9667, 0.9128,
        0.7250, 0.9000, 0.9188, 0.7222, 0.7667, 0.6833, 0.6111])
Train backdoor
Train Epoch: 20 [0/9728 (0%)]	Loss: 8.964411
Train Epoch: 20 [512/9728 (5%)]	Loss: 4.065440
Train Epoch: 20 [1024/9728 (11%)]	Loss: 0.235717
Train Epoch: 20 [1536/9728 (16%)]	Loss: 0.076961
Train Epoch: 20 [2048/9728 (21%)]	Loss: 0.028881
Train Epoch: 20 [2560/9728 (26%)]	Loss: 0.019381
Train Epoch: 20 [3072/9728 (32%)]	Loss: 0.014280
Train Epoch: 20 [3584/9728 (37%)]	Loss: 0.025964
Train Epoch: 20 [4096/9728 (42%)]	Loss: 0.009640
Train Epoch: 20 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 22 [0/39424 (0%)]	Loss: 10.748701
Train Epoch: 22 [512/39424 (1%)]	Loss: 1.184761
Train Epoch: 22 [1024/39424 (3%)]	Loss: 0.960729
Train Epoch: 22 [1536/39424 (4%)]	Loss: 0.909452
Train Epoch: 22 [2048/39424 (5%)]	Loss: 0.759875
Train Epoch: 22 [2560/39424 (6%)]	Loss: 0.732472
Train Epoch: 22 [3072/39424 (8%)]	Loss: 0.750117
Train Epoch: 22 [3584/39424 (9%)]	Loss: 0.666128
Train Epoch: 22 [4096/39424 (10%)]	Loss: 0.647107
Train Epoch: 22 [4608/39424 (12%)]	Loss: 0.646206
Train Epoch: 22 [5120/39424 (13%)]	Loss: 0.618328
Train Epoch: 22 [5632/39424 (14%)]	Loss: 0.594141
Train Epoch: 22 [6144/39424 (16%)]	Loss: 0.598784
Train Epoch: 22 [6656/39424 (17%)]	Loss: 0.627942
Train Epoch: 22 [7168/39424 (18%)]	Loss: 0.579697
Train Epoch: 22 [7680/39424 (19%)]	Loss: 0

Train Epoch: 24 [33792/39424 (86%)]	Loss: 0.300330
Train Epoch: 24 [34304/39424 (87%)]	Loss: 0.305534
Train Epoch: 24 [34816/39424 (88%)]	Loss: 0.355821
Train Epoch: 24 [35328/39424 (90%)]	Loss: 0.365810
Train Epoch: 24 [35840/39424 (91%)]	Loss: 0.336023
Train Epoch: 24 [36352/39424 (92%)]	Loss: 0.345763
Train Epoch: 24 [36864/39424 (94%)]	Loss: 0.328079
Train Epoch: 24 [37376/39424 (95%)]	Loss: 0.391989
Train Epoch: 24 [37888/39424 (96%)]	Loss: 0.378066
Train Epoch: 24 [38400/39424 (97%)]	Loss: 0.309094
Train Epoch: 24 [38912/39424 (99%)]	Loss: 0.348118
Average training loss: 0.5592924356460571

Test set: Average loss: 8.7872, Accuracy: 18/12630 (0%)

tensor([0.0014,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    

Train Epoch: 27 [5632/39424 (14%)]	Loss: 0.434714
Train Epoch: 27 [6144/39424 (16%)]	Loss: 0.403841
Train Epoch: 27 [6656/39424 (17%)]	Loss: 0.467426
Train Epoch: 27 [7168/39424 (18%)]	Loss: 0.436316
Train Epoch: 27 [7680/39424 (19%)]	Loss: 0.405997
Train Epoch: 27 [8192/39424 (21%)]	Loss: 0.346834
Train Epoch: 27 [8704/39424 (22%)]	Loss: 0.353352
Train Epoch: 27 [9216/39424 (23%)]	Loss: 0.389220
Train Epoch: 27 [9728/39424 (25%)]	Loss: 0.414891
Train Epoch: 27 [10240/39424 (26%)]	Loss: 0.364858
Train Epoch: 27 [10752/39424 (27%)]	Loss: 0.414801
Train Epoch: 27 [11264/39424 (29%)]	Loss: 0.380905
Train Epoch: 27 [11776/39424 (30%)]	Loss: 0.336696
Train Epoch: 27 [12288/39424 (31%)]	Loss: 0.358923
Train Epoch: 27 [12800/39424 (32%)]	Loss: 0.361596
Train Epoch: 27 [13312/39424 (34%)]	Loss: 0.375954
Train Epoch: 27 [13824/39424 (35%)]	Loss: 0.354278
Train Epoch: 27 [14336/39424 (36%)]	Loss: 0.327821
Train Epoch: 27 [14848/39424 (38%)]	Loss: 0.349667
Train Epoch: 27 [15360/39424 (39%)]	Loss

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.4385, Accuracy: 11314/12630 (90%)

tensor([0.0833, 0.9278, 0.9493, 0.9533, 0.9091, 0.8270, 0.7267, 0.8044, 0.8378,
        0.9771, 0.9682, 0.9190, 0.9609, 0.9694, 1.0000, 0.9476, 0.9533, 0.9306,
        0.7154, 0.5000, 0.9444, 0.5333, 0.9083, 0.8733, 0.8333, 0.9125, 0.7833,
        0.4500, 0.8600, 0.9667, 0.6600, 0.9481, 0.7000, 0.9810, 0.9750, 0.9462,
        0.8417, 0.9333, 0.9261, 0.7333, 0.8667, 0.7667, 0.8333])
Train backdoor
Train Epoch: 29 [0/9728 (0%)]	Loss: 8.492413
Train Epoch: 29 [512/9728 (5%)]	Loss: 3.121063
Train Epoch: 29 [1024/9728 (11%)]	Loss: 0.182562
Train Epoch: 29 [1536/9728 (16%)]	Loss: 0.063766
Train Epoch: 29 [2048/9728 (21%)]	Loss: 0.025463
Train Epoch: 29 [2560/9728 (26%)]	Loss: 0.031111
Train Epoch: 29 [3072/9728 (32%)]	Loss: 0.017768
Train Epoch: 29 [3584/9728 (37%)]	Loss: 0.019368
Train Epoch: 29 [4096/9728 (42%)]	Loss: 0.013817
Train Epoch: 29 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 31 [0/39424 (0%)]	Loss: 9.321207
Train Epoch: 31 [512/39424 (1%)]	Loss: 0.847836
Train Epoch: 31 [1024/39424 (3%)]	Loss: 0.640705
Train Epoch: 31 [1536/39424 (4%)]	Loss: 0.562576
Train Epoch: 31 [2048/39424 (5%)]	Loss: 0.450898
Train Epoch: 31 [2560/39424 (6%)]	Loss: 0.380094
Train Epoch: 31 [3072/39424 (8%)]	Loss: 0.444950
Train Epoch: 31 [3584/39424 (9%)]	Loss: 0.396968
Train Epoch: 31 [4096/39424 (10%)]	Loss: 0.391228
Train Epoch: 31 [4608/39424 (12%)]	Loss: 0.375972
Train Epoch: 31 [5120/39424 (13%)]	Loss: 0.340623
Train Epoch: 31 [5632/39424 (14%)]	Loss: 0.375912
Train Epoch: 31 [6144/39424 (16%)]	Loss: 0.339777
Train Epoch: 31 [6656/39424 (17%)]	Loss: 0.395727
Train Epoch: 31 [7168/39424 (18%)]	Loss: 0.355477
Train Epoch: 31 [7680/39424 (19%)]	Loss: 0.

Train Epoch: 33 [33792/39424 (86%)]	Loss: 0.184541
Train Epoch: 33 [34304/39424 (87%)]	Loss: 0.156269
Train Epoch: 33 [34816/39424 (88%)]	Loss: 0.206462
Train Epoch: 33 [35328/39424 (90%)]	Loss: 0.246061
Train Epoch: 33 [35840/39424 (91%)]	Loss: 0.204487
Train Epoch: 33 [36352/39424 (92%)]	Loss: 0.205417
Train Epoch: 33 [36864/39424 (94%)]	Loss: 0.202914
Train Epoch: 33 [37376/39424 (95%)]	Loss: 0.218472
Train Epoch: 33 [37888/39424 (96%)]	Loss: 0.239168
Train Epoch: 33 [38400/39424 (97%)]	Loss: 0.195124
Train Epoch: 33 [38912/39424 (99%)]	Loss: 0.208092
Average training loss: 0.39250198006629944

Test set: Average loss: 8.6112, Accuracy: 27/12630 (0%)

tensor([0.0021,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,   

Train Epoch: 36 [5632/39424 (14%)]	Loss: 0.313883
Train Epoch: 36 [6144/39424 (16%)]	Loss: 0.284144
Train Epoch: 36 [6656/39424 (17%)]	Loss: 0.301286
Train Epoch: 36 [7168/39424 (18%)]	Loss: 0.299278
Train Epoch: 36 [7680/39424 (19%)]	Loss: 0.279708
Train Epoch: 36 [8192/39424 (21%)]	Loss: 0.240048
Train Epoch: 36 [8704/39424 (22%)]	Loss: 0.244026
Train Epoch: 36 [9216/39424 (23%)]	Loss: 0.287626
Train Epoch: 36 [9728/39424 (25%)]	Loss: 0.279694
Train Epoch: 36 [10240/39424 (26%)]	Loss: 0.247997
Train Epoch: 36 [10752/39424 (27%)]	Loss: 0.299268
Train Epoch: 36 [11264/39424 (29%)]	Loss: 0.253306
Train Epoch: 36 [11776/39424 (30%)]	Loss: 0.246559
Train Epoch: 36 [12288/39424 (31%)]	Loss: 0.251920
Train Epoch: 36 [12800/39424 (32%)]	Loss: 0.230127
Train Epoch: 36 [13312/39424 (34%)]	Loss: 0.244038
Train Epoch: 36 [13824/39424 (35%)]	Loss: 0.255513
Train Epoch: 36 [14336/39424 (36%)]	Loss: 0.222463
Train Epoch: 36 [14848/39424 (38%)]	Loss: 0.258484
Train Epoch: 36 [15360/39424 (39%)]	Loss

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.3563, Accuracy: 11587/12630 (92%)

tensor([0.2167, 0.9375, 0.9720, 0.9578, 0.9152, 0.8698, 0.7667, 0.8311, 0.9022,
        0.9875, 0.9833, 0.9381, 0.9783, 0.9861, 1.0000, 0.9714, 0.9667, 0.9333,
        0.7795, 0.6333, 0.9667, 0.6222, 0.9167, 0.9333, 0.8556, 0.9229, 0.7889,
        0.5000, 0.9267, 0.9667, 0.7133, 0.9667, 0.6167, 0.9857, 0.9833, 0.9538,
        0.8667, 0.9833, 0.9333, 0.7556, 0.8444, 0.8167, 0.8889])
Train backdoor
Train Epoch: 38 [0/9728 (0%)]	Loss: 8.198919
Train Epoch: 38 [512/9728 (5%)]	Loss: 2.801678
Train Epoch: 38 [1024/9728 (11%)]	Loss: 0.126180
Train Epoch: 38 [1536/9728 (16%)]	Loss: 0.062070
Train Epoch: 38 [2048/9728 (21%)]	Loss: 0.027172
Train Epoch: 38 [2560/9728 (26%)]	Loss: 0.023751
Train Epoch: 38 [3072/9728 (32%)]	Loss: 0.020640
Train Epoch: 38 [3584/9728 (37%)]	Loss: 0.026617
Train Epoch: 38 [4096/9728 (42%)]	Loss: 0.015566
Train Epoch: 38 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 40 [0/39424 (0%)]	Loss: 8.544490
Train Epoch: 40 [512/39424 (1%)]	Loss: 0.771029
Train Epoch: 40 [1024/39424 (3%)]	Loss: 0.622575
Train Epoch: 40 [1536/39424 (4%)]	Loss: 0.559013
Train Epoch: 40 [2048/39424 (5%)]	Loss: 0.427533
Train Epoch: 40 [2560/39424 (6%)]	Loss: 0.352807
Train Epoch: 40 [3072/39424 (8%)]	Loss: 0.384972
Train Epoch: 40 [3584/39424 (9%)]	Loss: 0.308928
Train Epoch: 40 [4096/39424 (10%)]	Loss: 0.284733
Train Epoch: 40 [4608/39424 (12%)]	Loss: 0.297689
Train Epoch: 40 [5120/39424 (13%)]	Loss: 0.257720
Train Epoch: 40 [5632/39424 (14%)]	Loss: 0.267389
Train Epoch: 40 [6144/39424 (16%)]	Loss: 0.247582
Train Epoch: 40 [6656/39424 (17%)]	Loss: 0.263535
Train Epoch: 40 [7168/39424 (18%)]	Loss: 0.272712
Train Epoch: 40 [7680/39424 (19%)]	Loss: 0.

Train Epoch: 42 [33792/39424 (86%)]	Loss: 0.138615
Train Epoch: 42 [34304/39424 (87%)]	Loss: 0.106079
Train Epoch: 42 [34816/39424 (88%)]	Loss: 0.141577
Train Epoch: 42 [35328/39424 (90%)]	Loss: 0.139612
Train Epoch: 42 [35840/39424 (91%)]	Loss: 0.121740
Train Epoch: 42 [36352/39424 (92%)]	Loss: 0.151897
Train Epoch: 42 [36864/39424 (94%)]	Loss: 0.151669
Train Epoch: 42 [37376/39424 (95%)]	Loss: 0.166843
Train Epoch: 42 [37888/39424 (96%)]	Loss: 0.168937
Train Epoch: 42 [38400/39424 (97%)]	Loss: 0.153721
Train Epoch: 42 [38912/39424 (99%)]	Loss: 0.159276
Average training loss: 0.3240828514099121

Test set: Average loss: 8.3332, Accuracy: 52/12630 (0%)

tensor([0.0041,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    

Train Epoch: 45 [5632/39424 (14%)]	Loss: 0.255902
Train Epoch: 45 [6144/39424 (16%)]	Loss: 0.228900
Train Epoch: 45 [6656/39424 (17%)]	Loss: 0.239821
Train Epoch: 45 [7168/39424 (18%)]	Loss: 0.215505
Train Epoch: 45 [7680/39424 (19%)]	Loss: 0.233429
Train Epoch: 45 [8192/39424 (21%)]	Loss: 0.179837
Train Epoch: 45 [8704/39424 (22%)]	Loss: 0.207349
Train Epoch: 45 [9216/39424 (23%)]	Loss: 0.217650
Train Epoch: 45 [9728/39424 (25%)]	Loss: 0.240322
Train Epoch: 45 [10240/39424 (26%)]	Loss: 0.193120
Train Epoch: 45 [10752/39424 (27%)]	Loss: 0.222035
Train Epoch: 45 [11264/39424 (29%)]	Loss: 0.183932
Train Epoch: 45 [11776/39424 (30%)]	Loss: 0.184227
Train Epoch: 45 [12288/39424 (31%)]	Loss: 0.200743
Train Epoch: 45 [12800/39424 (32%)]	Loss: 0.179760
Train Epoch: 45 [13312/39424 (34%)]	Loss: 0.188314
Train Epoch: 45 [13824/39424 (35%)]	Loss: 0.206919
Train Epoch: 45 [14336/39424 (36%)]	Loss: 0.170741
Train Epoch: 45 [14848/39424 (38%)]	Loss: 0.184212
Train Epoch: 45 [15360/39424 (39%)]	Loss

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.3125, Accuracy: 11730/12630 (93%)

tensor([0.3167, 0.9514, 0.9800, 0.9644, 0.9182, 0.8889, 0.8000, 0.8822, 0.9311,
        0.9875, 0.9864, 0.9595, 0.9754, 0.9944, 1.0000, 0.9714, 0.9867, 0.9417,
        0.7923, 0.8167, 0.9778, 0.6333, 0.9167, 0.9400, 0.8556, 0.9292, 0.7944,
        0.5000, 0.9467, 0.9667, 0.7067, 0.9815, 0.6000, 0.9905, 0.9833, 0.9487,
        0.9000, 0.9833, 0.9435, 0.7444, 0.8444, 0.8667, 0.9111])
Train backdoor
Train Epoch: 47 [0/9728 (0%)]	Loss: 7.888075
Train Epoch: 47 [512/9728 (5%)]	Loss: 2.794705
Train Epoch: 47 [1024/9728 (11%)]	Loss: 0.128319
Train Epoch: 47 [1536/9728 (16%)]	Loss: 0.064932
Train Epoch: 47 [2048/9728 (21%)]	Loss: 0.039340
Train Epoch: 47 [2560/9728 (26%)]	Loss: 0.030955
Train Epoch: 47 [3072/9728 (32%)]	Loss: 0.019676
Train Epoch: 47 [3584/9728 (37%)]	Loss: 0.020421
Train Epoch: 47 [4096/9728 (42%)]	Loss: 0.012828
Train Epoch: 47 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 49 [0/39424 (0%)]	Loss: 7.723584
Train Epoch: 49 [512/39424 (1%)]	Loss: 0.567014
Train Epoch: 49 [1024/39424 (3%)]	Loss: 0.408248
Train Epoch: 49 [1536/39424 (4%)]	Loss: 0.354363
Train Epoch: 49 [2048/39424 (5%)]	Loss: 0.294326
Train Epoch: 49 [2560/39424 (6%)]	Loss: 0.254279
Train Epoch: 49 [3072/39424 (8%)]	Loss: 0.293122
Train Epoch: 49 [3584/39424 (9%)]	Loss: 0.268415
Train Epoch: 49 [4096/39424 (10%)]	Loss: 0.237902
Train Epoch: 49 [4608/39424 (12%)]	Loss: 0.231198
Train Epoch: 49 [5120/39424 (13%)]	Loss: 0.213217
Train Epoch: 49 [5632/39424 (14%)]	Loss: 0.230728
Train Epoch: 49 [6144/39424 (16%)]	Loss: 0.204818
Train Epoch: 49 [6656/39424 (17%)]	Loss: 0.224038
Train Epoch: 49 [7168/39424 (18%)]	Loss: 0.209077
Train Epoch: 49 [7680/39424 (19%)]	Loss: 0.

Train Epoch: 51 [33792/39424 (86%)]	Loss: 0.088077
Train Epoch: 51 [34304/39424 (87%)]	Loss: 0.092392
Train Epoch: 51 [34816/39424 (88%)]	Loss: 0.115892
Train Epoch: 51 [35328/39424 (90%)]	Loss: 0.114694
Train Epoch: 51 [35840/39424 (91%)]	Loss: 0.135289
Train Epoch: 51 [36352/39424 (92%)]	Loss: 0.113156
Train Epoch: 51 [36864/39424 (94%)]	Loss: 0.104084
Train Epoch: 51 [37376/39424 (95%)]	Loss: 0.118229
Train Epoch: 51 [37888/39424 (96%)]	Loss: 0.136069
Train Epoch: 51 [38400/39424 (97%)]	Loss: 0.106572
Train Epoch: 51 [38912/39424 (99%)]	Loss: 0.119475
Average training loss: 0.2660347819328308

Test set: Average loss: 8.1245, Accuracy: 56/12630 (0%)

tensor([0.0044,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    

Train Epoch: 54 [5632/39424 (14%)]	Loss: 0.204012
Train Epoch: 54 [6144/39424 (16%)]	Loss: 0.187221
Train Epoch: 54 [6656/39424 (17%)]	Loss: 0.199263
Train Epoch: 54 [7168/39424 (18%)]	Loss: 0.196757
Train Epoch: 54 [7680/39424 (19%)]	Loss: 0.195635
Train Epoch: 54 [8192/39424 (21%)]	Loss: 0.155664
Train Epoch: 54 [8704/39424 (22%)]	Loss: 0.167842
Train Epoch: 54 [9216/39424 (23%)]	Loss: 0.190814
Train Epoch: 54 [9728/39424 (25%)]	Loss: 0.179658
Train Epoch: 54 [10240/39424 (26%)]	Loss: 0.154498
Train Epoch: 54 [10752/39424 (27%)]	Loss: 0.205974
Train Epoch: 54 [11264/39424 (29%)]	Loss: 0.156274
Train Epoch: 54 [11776/39424 (30%)]	Loss: 0.148347
Train Epoch: 54 [12288/39424 (31%)]	Loss: 0.159976
Train Epoch: 54 [12800/39424 (32%)]	Loss: 0.149852
Train Epoch: 54 [13312/39424 (34%)]	Loss: 0.167477
Train Epoch: 54 [13824/39424 (35%)]	Loss: 0.171870
Train Epoch: 54 [14336/39424 (36%)]	Loss: 0.145760
Train Epoch: 54 [14848/39424 (38%)]	Loss: 0.146279
Train Epoch: 54 [15360/39424 (39%)]	Loss

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.2816, Accuracy: 11822/12630 (94%)

tensor([0.3667, 0.9583, 0.9840, 0.9578, 0.9303, 0.9016, 0.8000, 0.9044, 0.9622,
        0.9875, 0.9864, 0.9595, 0.9768, 0.9958, 1.0000, 0.9762, 0.9867, 0.9417,
        0.7974, 0.9500, 0.9889, 0.6444, 0.9250, 0.9467, 0.8778, 0.9333, 0.8111,
        0.5000, 0.9533, 0.9667, 0.7400, 0.9815, 0.6333, 0.9905, 0.9833, 0.9513,
        0.9083, 1.0000, 0.9536, 0.7667, 0.8556, 0.8833, 0.8889])
Train backdoor
Train Epoch: 56 [0/9728 (0%)]	Loss: 7.467158
Train Epoch: 56 [512/9728 (5%)]	Loss: 2.594823
Train Epoch: 56 [1024/9728 (11%)]	Loss: 0.146795
Train Epoch: 56 [1536/9728 (16%)]	Loss: 0.071985
Train Epoch: 56 [2048/9728 (21%)]	Loss: 0.044120
Train Epoch: 56 [2560/9728 (26%)]	Loss: 0.040602
Train Epoch: 56 [3072/9728 (32%)]	Loss: 0.023550
Train Epoch: 56 [3584/9728 (37%)]	Loss: 0.022050
Train Epoch: 56 [4096/9728 (42%)]	Loss: 0.015444
Train Epoch: 56 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 58 [0/39424 (0%)]	Loss: 7.366017
Train Epoch: 58 [512/39424 (1%)]	Loss: 0.494390
Train Epoch: 58 [1024/39424 (3%)]	Loss: 0.396741
Train Epoch: 58 [1536/39424 (4%)]	Loss: 0.349624
Train Epoch: 58 [2048/39424 (5%)]	Loss: 0.281712
Train Epoch: 58 [2560/39424 (6%)]	Loss: 0.232590
Train Epoch: 58 [3072/39424 (8%)]	Loss: 0.275633
Train Epoch: 58 [3584/39424 (9%)]	Loss: 0.228226
Train Epoch: 58 [4096/39424 (10%)]	Loss: 0.207922
Train Epoch: 58 [4608/39424 (12%)]	Loss: 0.200567
Train Epoch: 58 [5120/39424 (13%)]	Loss: 0.194026
Train Epoch: 58 [5632/39424 (14%)]	Loss: 0.216310
Train Epoch: 58 [6144/39424 (16%)]	Loss: 0.170780
Train Epoch: 58 [6656/39424 (17%)]	Loss: 0.200809
Train Epoch: 58 [7168/39424 (18%)]	Loss: 0.179374
Train Epoch: 58 [7680/39424 (19%)]	Loss: 0.

Train Epoch: 60 [33792/39424 (86%)]	Loss: 0.081842
Train Epoch: 60 [34304/39424 (87%)]	Loss: 0.067807
Train Epoch: 60 [34816/39424 (88%)]	Loss: 0.096052
Train Epoch: 60 [35328/39424 (90%)]	Loss: 0.104582
Train Epoch: 60 [35840/39424 (91%)]	Loss: 0.088525
Train Epoch: 60 [36352/39424 (92%)]	Loss: 0.102862
Train Epoch: 60 [36864/39424 (94%)]	Loss: 0.083824
Train Epoch: 60 [37376/39424 (95%)]	Loss: 0.092017
Train Epoch: 60 [37888/39424 (96%)]	Loss: 0.122197
Train Epoch: 60 [38400/39424 (97%)]	Loss: 0.095057
Train Epoch: 60 [38912/39424 (99%)]	Loss: 0.088423
Average training loss: 0.23908741772174835

Test set: Average loss: 7.8668, Accuracy: 79/12630 (1%)

tensor([0.0063,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,   

Train Epoch: 63 [5632/39424 (14%)]	Loss: 0.202405
Train Epoch: 63 [6144/39424 (16%)]	Loss: 0.154390
Train Epoch: 63 [6656/39424 (17%)]	Loss: 0.181501
Train Epoch: 63 [7168/39424 (18%)]	Loss: 0.187429
Train Epoch: 63 [7680/39424 (19%)]	Loss: 0.175660
Train Epoch: 63 [8192/39424 (21%)]	Loss: 0.122600
Train Epoch: 63 [8704/39424 (22%)]	Loss: 0.146676
Train Epoch: 63 [9216/39424 (23%)]	Loss: 0.159924
Train Epoch: 63 [9728/39424 (25%)]	Loss: 0.163139
Train Epoch: 63 [10240/39424 (26%)]	Loss: 0.143120
Train Epoch: 63 [10752/39424 (27%)]	Loss: 0.173887
Train Epoch: 63 [11264/39424 (29%)]	Loss: 0.129348
Train Epoch: 63 [11776/39424 (30%)]	Loss: 0.118027
Train Epoch: 63 [12288/39424 (31%)]	Loss: 0.136199
Train Epoch: 63 [12800/39424 (32%)]	Loss: 0.118124
Train Epoch: 63 [13312/39424 (34%)]	Loss: 0.124601
Train Epoch: 63 [13824/39424 (35%)]	Loss: 0.138702
Train Epoch: 63 [14336/39424 (36%)]	Loss: 0.124675
Train Epoch: 63 [14848/39424 (38%)]	Loss: 0.132120
Train Epoch: 63 [15360/39424 (39%)]	Loss

           nan,    nan,    nan,    nan,    nan,    nan,    nan])

Test set: Average loss: 0.2632, Accuracy: 11870/12630 (94%)

tensor([0.4667, 0.9639, 0.9813, 0.9600, 0.9348, 0.9175, 0.8067, 0.9089, 0.9689,
        0.9833, 0.9864, 0.9595, 0.9783, 0.9958, 1.0000, 0.9762, 0.9933, 0.9444,
        0.7974, 0.9833, 0.9889, 0.6444, 0.9250, 0.9667, 0.8778, 0.9375, 0.8167,
        0.5000, 0.9600, 0.9667, 0.7333, 0.9815, 0.6667, 0.9905, 0.9917, 0.9641,
        0.9250, 1.0000, 0.9565, 0.7556, 0.8667, 0.8667, 0.8889])
Train backdoor
Train Epoch: 65 [0/9728 (0%)]	Loss: 7.240137
Train Epoch: 65 [512/9728 (5%)]	Loss: 2.461882
Train Epoch: 65 [1024/9728 (11%)]	Loss: 0.155498
Train Epoch: 65 [1536/9728 (16%)]	Loss: 0.099899
Train Epoch: 65 [2048/9728 (21%)]	Loss: 0.045335
Train Epoch: 65 [2560/9728 (26%)]	Loss: 0.038403
Train Epoch: 65 [3072/9728 (32%)]	Loss: 0.024329
Train Epoch: 65 [3584/9728 (37%)]	Loss: 0.020226
Train Epoch: 65 [4096/9728 (42%)]	Loss: 0.015252
Train Epoch: 65 [4608/9728 (47%)]	Loss


tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])
Train benign dataset
Train Epoch: 67 [0/39424 (0%)]	Loss: 7.134238
Train Epoch: 67 [512/39424 (1%)]	Loss: 0.406966
Train Epoch: 67 [1024/39424 (3%)]	Loss: 0.314701
Train Epoch: 67 [1536/39424 (4%)]	Loss: 0.284153
Train Epoch: 67 [2048/39424 (5%)]	Loss: 0.229936
Train Epoch: 67 [2560/39424 (6%)]	Loss: 0.200068
Train Epoch: 67 [3072/39424 (8%)]	Loss: 0.240063
Train Epoch: 67 [3584/39424 (9%)]	Loss: 0.213519
Train Epoch: 67 [4096/39424 (10%)]	Loss: 0.182583
Train Epoch: 67 [4608/39424 (12%)]	Loss: 0.184428
Train Epoch: 67 [5120/39424 (13%)]	Loss: 0.169183
Train Epoch: 67 [5632/39424 (14%)]	Loss: 0.188143
Train Epoch: 67 [6144/39424 (16%)]	Loss: 0.150188
Train Epoch: 67 [6656/39424 (17%)]	Loss: 0.172560
Train Epoch: 67 [7168/39424 (18%)]	Loss: 0.165054
Train Epoch: 67 [7680/39424 (19%)]	Loss: 0.

Train Epoch: 69 [33792/39424 (86%)]	Loss: 0.066072
Train Epoch: 69 [34304/39424 (87%)]	Loss: 0.067607
Train Epoch: 69 [34816/39424 (88%)]	Loss: 0.078001
Train Epoch: 69 [35328/39424 (90%)]	Loss: 0.096005
Train Epoch: 69 [35840/39424 (91%)]	Loss: 0.074257
Train Epoch: 69 [36352/39424 (92%)]	Loss: 0.080759
Train Epoch: 69 [36864/39424 (94%)]	Loss: 0.076149
Train Epoch: 69 [37376/39424 (95%)]	Loss: 0.087465
Train Epoch: 69 [37888/39424 (96%)]	Loss: 0.095852
Train Epoch: 69 [38400/39424 (97%)]	Loss: 0.083619
Train Epoch: 69 [38912/39424 (99%)]	Loss: 0.091815
Average training loss: 0.21457646787166595

Test set: Average loss: 7.6185, Accuracy: 100/12630 (1%)

tensor([0.0079,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,  

Train Epoch: 72 [5632/39424 (14%)]	Loss: 0.180521
Train Epoch: 72 [6144/39424 (16%)]	Loss: 0.146656
Train Epoch: 72 [6656/39424 (17%)]	Loss: 0.162746
Train Epoch: 72 [7168/39424 (18%)]	Loss: 0.146585
Train Epoch: 72 [7680/39424 (19%)]	Loss: 0.157812
Train Epoch: 72 [8192/39424 (21%)]	Loss: 0.113913
Train Epoch: 72 [8704/39424 (22%)]	Loss: 0.142196
Train Epoch: 72 [9216/39424 (23%)]	Loss: 0.148297
Train Epoch: 72 [9728/39424 (25%)]	Loss: 0.135097
Train Epoch: 72 [10240/39424 (26%)]	Loss: 0.133062
Train Epoch: 72 [10752/39424 (27%)]	Loss: 0.147441
Train Epoch: 72 [11264/39424 (29%)]	Loss: 0.114457
Train Epoch: 72 [11776/39424 (30%)]	Loss: 0.112548
Train Epoch: 72 [12288/39424 (31%)]	Loss: 0.107556
Train Epoch: 72 [12800/39424 (32%)]	Loss: 0.110248
Train Epoch: 72 [13312/39424 (34%)]	Loss: 0.115811
Train Epoch: 72 [13824/39424 (35%)]	Loss: 0.114612
Train Epoch: 72 [14336/39424 (36%)]	Loss: 0.107224
Train Epoch: 72 [14848/39424 (38%)]	Loss: 0.110247
Train Epoch: 72 [15360/39424 (39%)]	Loss

KeyboardInterrupt: 

In [ ]:
#model = Net().to(device)
#model.load_state_dict(torch.load("newfaces_alexnet_224x224_augmented100.pt"))
#test(model, device, test_loader)


In [16]:
model = Net().to(device)
model

Net(
  (conv0): Conv2d(3, 16, kernel_size=(5, 5), stride=(1, 1))
  (bn0): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv1): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1))
  (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool_0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(32, 96, kernel_size=(3, 3), stride=(1, 1))
  (bn2): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(96, 256, kernel_size=(3, 3), stride=(1, 1))
  (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool_1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (dropout0): Dropout2d(p=0.37, inplace=False)
  (fc0): Linear(in_features=4096, out_features=2048, bias=True)
  (dropout1): Dropout2d(p=0.37, inplace=False)
  (fc1): Linear(in_features=2048, out_features=1024, bias=True